# bindake[autoboot,overlay-command-output]: <Super>+<Ctrl>+f
firefox:
	if pgrep -x firefox-bin > /dev/null; then \
		wmctrl -xa firefox; \
	else \
		firefox & \
	fi; \
	echo "Firefox Browser"

# bindake: <Super>+<Ctrl>+g
chrome:
	if pgrep -x chrome > /dev/null; then \
		wmctrl -xa google-chrome; \
	else \
		setsid google-chrome > /dev/null 2>&1 < /dev/null & \
	fi; \
	echo "Chrome Browser"

other-cmd:
	ls -la
