
# bindake: Cmd R+Shift r+F
firefox:
	if pgrep -x firefox-bin > /dev/null; then \
		wmctrl -xa firefox; \
	else \
		firefox & \
	fi; \
	echo "Firefox Browser"

# bindake: Cmd R+Shift r+C
chrome:
    if pgrep -x chrome > /dev/null; then
        wmctrl -xa google-chrome
    else
        google-chrome &
    fi
    echo "Chrome Browser

other-cmd:
    ls -la
